#!/bin/bash
echo "***********************"
echo "Getting Git Submodules:"
echo "***********************"
git submodule update --init

BACKUP="$HOME/dotfiles.bak"
echo "***********************"
echo "Creating Backup Directory @ $BACKUP"
echo "***********************"
rm -rf $BACKUP 2> /dev/null
mkdir $BACKUP

echo "***********************"
echo "Creating Links"
echo "***********************"

DIRS=`find . -name "*.symlink" | grep -v "^\.\/\.git" | sed 's/\/$//'`;
for DIR in $DIRS
do
  DIRNAME=${DIR##*/}
  FILE=`echo $DIRNAME | sed 's/\.symlink//' | sed 's/^\.\///'`
  DIR=`echo $DIR |  sed 's/^\.\///'`
  #**BACKUP**#
  echo "Moving $HOME/.$FILE => $BACKUP/${FILE}.symlink, (if it exists)"
  mv $HOME/.$FILE $BACKUP/${FILE}.symlink 2> /dev/null
  echo "Linking $DIR -> $HOME/.$FILE"
  ln -s $PWD/$DIR $HOME/.$FILE
done
