#!/bin/bash
echo "***********************"
echo "Getting Git Submodules:"
echo "***********************"
git submodule update --init

DATE=`date '+%Y-%m-%d'`
BACKUP="$HOME/dotfiles_circa_$DATE"
echo "***********************"
echo "Creating Backup Directory @ $BACKUP"
echo "***********************"
rm -rf $BACKUP > /dev/null
mkdir $BACKUP

echo "***********************"
echo "Creating Links"
echo "***********************"

DIRS=`find . -name "*.symlink" | grep -v "^\.\/\.git" | sed 's/\/$//'`;
for DIR in $DIRS
do
  DIRNAME=${DIR##*/}
  FILE=`echo $DIRNAME | sed 's/\.symlink//' | sed 's/^\.\///'`
  DIR=`echo $DIR |  sed 's/^\.\///'`
  #**BACKUP**#
  #mkdir so copy wont bitch
  echo "Moving $HOME/.$FILE => $BACKUP/$DIR, (if it exists)"
  mkdir -p $BACKUP/$DIR
  mv $HOME/.$FILE $BACKUP/$DIR 2> /dev/null
  echo "Linking $DIR -> $HOME/.$FILE"
  ln -s $PWD/$DIR $HOME/.$FILE
done
