#!/usr/bin/env bash
PACKAGE_MANAGER=`./setup_scripts/find_package_manager`
\curl -L https://get.rvm.io | bash -s stable --ruby
$PACKAGE_MANAGER install zsh
$PACKAGE_MANAGER install vim
$PACKAGE_MANAGER install tmux
$PACKAGE_MANAGER install ag
$PACKAGE_MANAGER install ruby
