#Join the dots
  alias v='vim'
  alias cdf='cd ~/dotfiles/'
  alias e='cd ~/workspace/exchange'
  alias p='cd ~/workspace/pos.rb'
  alias c='cd ~/workspace/carbon'
  alias ct='cd ~/workspace/cheaptickets'
  alias r='rails'
  alias t='/usr/local/Cellar/todo-txt/2.9/bin/todo.sh -d $HOME/Dropbox/todo/todo.cfg'
  alias todo='vim ~/Dropbox/todo/todo.txt'
  alias becsl='bundle exec cap staging log'
  alias becsbl='bundle exec cap sandbox log'
  alias becpl='bundle exec cap production log'
