#!/bin/sh
managers=(yum apt-get brew)
FOUND_MANAGER=false
for manager in ${managers[*]}
do
  if type -p $manager > /dev/null; then 
    FOUND_MANAGER=true
    echo "$manager";
    break
  fi
done

if ! $FOUND_MANAGER; then
  echo "NO PACKAGE MANAGER FOUND"
  echo "one of the following package managers is required: "
  for manager in ${managers[*]}
  do
    echo "  - $manager"
  done
fi
#case `uname` in
#  Linux ) 
#    LINUX=1
#    which yum && { echo centos; return; } 
#    which zypper && { echo opensuse; return; }
#    which apt-get && { echo debian; return; }
#    ;;
#  Darwin )
#    echo darwin;
#    ;;
#  * )
#    ;;
#esac
