#!/bin/bash
OPS3=$PS3
PS3="Would You Like To Overwrite All Existing Links?"
select task in "Yes" \
  "No" \
  "Cancel"
do 
  case $REPLY in
    1) 
      OVERWRITE=1
      break
      ;;
    2)
      OVERWRITE=0
      break
      ;;
    3)
      echo 'Cancelling the linking process, if you have existing links that you dont want to overwrite please back them up at this point'
      exit 1
      ;;
    *)
      exit 1 ;;
  esac
done

for symlink in ~/dotfiles/*.symlink && ~/dotfiles/**/*.symlink
do
  echo $symlink
done
