#!/bin/sh
case `uname` in
  Linux ) 
    LINUX=1
    which yum && { echo centos; return; } 
    which zypper && { echo opensuse; return; }
    which apt-get && { echo debian; return; }
    ;;
  Darwin )
    echo darwin;
    ;;
  * )
    ;;
esac
