#!/bin/bash
# Create a new rails app from JoeQuery's Rails Template.
# arg1: appName
function rails_template(){
  appName=$1
  printf "\n##############################################\n"
  printf "# Cloning template\n"
  printf "##############################################\n"
  git clone git://github.com/Hack56/Rails-Template.git

  printf "\n##############################################\n"
  printf "# Renaming directory\n"
  printf "##############################################\n"
  printf "Renaming Rails-Template directory to %s...\n" "$appName"
  mv Rails-Template $appName
  cd $appName
  printf "Current working directory has changed to %s...\n" "$PWD"

  printf "\n##############################################\n"
  printf "# Installing gems via bundle\n"
  printf "##############################################\n"
  bundle install

  printf "\n##############################################\n"
  printf "# Renaming rails appp\n"
  printf "##############################################\n"
  printf "Renaming rails app to %s...\n" "$appName"
  bundle exec rails g rename_to $appName
}
